name: Development CSS Lint

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  css-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Stylelint
        run: npm install -g stylelint stylelint-config-standard
      - name: Lint CSS Files
        run: stylelint "**/*.css"
