name: Production CSS Lint

on:
  push:
    branches: [production]
  pull_request:
    branches: [production]

jobs:
  css-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Stylelint
        run: npm install -g stylelint stylelint-config-standard
      - name: Lint CSS Files
        run: stylelint "**/*.css"
