name: Release HTML Lint

on:
  push:
    branches: [release]
  pull_request:
    branches: [release]

jobs:
  html-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install HTMLHint
        run: npm install -g htmlhint
      - name: Lint HTML Files
        run: htmlhint "**/*.html"
